### ISSUE TITLE
Unable to determine ClassLinker field offsets on Android R

### ISSUE THREAD

**Issue by enovella** [frida/frida-java-bridge#163]
## Setup
- Frida: 12.9.2 and own compiled from master
- Mobile: Google Pixel3a
- Android OS: Android R DP4 (Developer Preview 4)

The release version will be increased when Android R is not in beta phase:
```sh
sargo:/ # getprop |grep ro.build.version.sdk                                                                                                                                
[ro.build.version.sdk]: [29]
sargo:/ # getprop |grep ro.build.version.release                                                                                                                            
[ro.build.version.release]: [10]
[ro.build.version.release_or_codename]: [R]
```

## Crash
Related to this PR https://github.com/frida/frida-java-bridge/pull/159

```sh
--------- beginning of crash
libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 8341 (gum-js-loop), pid 1454 (system_server)
DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
DEBUG   : Build fingerprint: 'google/sargo/sargo:10/RPP4.200409.015/6455311:user/release-keys'
DEBUG   : Revision: 'MP1.0'
DEBUG   : ABI: 'arm64'
DEBUG   : Timestamp: 2020-05-16 21:16:55+0200
DEBUG   : pid: 1454, tid: 8341, name: gum-js-loop  >>> system_server <<<
DEBUG   : uid: 1000
DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
DEBUG   : Abort message: 'Error: Unable to determine ClassLinker field offsets
DEBUG   :     at ke (frida/node_modules/frida-java-bridge/lib/android.js:302:1)
DEBUG   :     at frida/node_modules/frida-java-bridge/lib/android.js:1337:1
DEBUG   :     at he (frida/node_modules/frida-java-bridge/lib/android.js:174:1)
DEBUG   :     at fe (frida/node_modules/frida-java-bridge/lib/android.js:12:1)
DEBUG   :     at m._tryInitialize (frida/node_modules/frida-java-bridge/index.js:15:1)
DEBUG   :     at new m (frida/node_modules/frida-java-bridge/index.js:8:1)
DEBUG   :     at Object.4../lib/android (frida/node_modules/frida-java-bridge/index.js:271:1)
DEBUG   :     at o (frida/node_modules/browser-pack/_prelude.js:1:1)
DEBUG   :     at frida/node_modules/browser-pack/_prelude.js:1:1
DEBUG   :     at Object.17.frida-java-bridge (frida/runtime/java.js:1:1)'
DEBUG   :     x0  0000000000000000  x1  0000000000002095  x2  0000000000000006  x3  000000746809da80
DEBUG   :     x4  fefefefefeff2830  x5  fefefefefeff2830  x6  fefefefefeff2830  x7  7f7f7f7f7f7f7f7f
DEBUG   :     x8  00000000000000f0  x9  733f828d5d334379  x10 0000000000000001  x11 0000000000000000
DEBUG   :     x12 ffffffc0fffffbdf  x13 00000000000002db  x14 00000000cfc68394  x15 002e461c6265a172
DEBUG   :     x16 00000077b44fdc80  x17 00000077b44df8f0  x18 0000000000000000  x19 00000000000005ae
DEBUG   :     x20 0000000000002095  x21 00000000ffffffff  x22 0000000000000000  x23 000000746809f000
DEBUG   :     x24 0000000000000000  x25 00000074182239c8  x26 00000073080b3085  x27 000000746809f000
DEBUG   :     x28 0000007300009660  x29 000000746809db00
DEBUG   :     lr  00000077b4492f6c  sp  000000746809d9d0  pc  00000077b4492f98  pst 0000000000000000
DEBUG   :
DEBUG   : backtrace:
DEBUG   :       #00 pc 000000000004df98  /apex/com.android.runtime/lib64/bionic/libc.so!libc.so (offset 0x4d000) (abort+212) (BuildId: 9c83fb1f8263902f3dd27421293358bf)
```
## Issue

The function `_getArtClassLinkerSpec` returns `null` and the exception is thrown. Did some debugging on it and it looks like `if (value.equals(internTable))` never is true so `delta` doesnt get assigned.
```java
function _getArtClassLinkerSpec (api) {
  /*
   * On Android 5.x:
   *
   * class ClassLinker {
   * ...
   * InternTable* intern_table_;                          <-- We find this then calculate our way forwards
   * const void* portable_resolution_trampoline_;
   * const void* quick_resolution_trampoline_;
   * const void* portable_imt_conflict_trampoline_;
   * const void* quick_imt_conflict_trampoline_;
   * const void* quick_generic_jni_trampoline_;           <-- ...to this
   * const void* quick_to_interpreter_bridge_trampoline_;
   * ...
   * }
   *
   * On Android 6.x and above:
   *
   * class ClassLinker {
   * ...
   * InternTable* intern_table_;                          <-- We find this then calculate our way forwards
   * const void* quick_resolution_trampoline_;
   * const void* quick_imt_conflict_trampoline_;
   * const void* quick_generic_jni_trampoline_;           <-- ...to this
   * const void* quick_to_interpreter_bridge_trampoline_;
   * ...
   * }
   */

  const runtime = api.artRuntime;
  const runtimeSpec = getArtRuntimeSpec(api);

  const classLinker = runtime.add(runtimeSpec.offset.classLinker).readPointer();
  const internTable = runtime.add(runtimeSpec.offset.internTable).readPointer();

  const startOffset = (pointerSize === 4) ? 100 : 200;
  const endOffset = startOffset + (100 * pointerSize);

  const apiLevel = getAndroidApiLevel();

  let spec = null;

  for (let offset = startOffset; offset !== endOffset; offset += pointerSize) {
    const value = classLinker.add(offset).readPointer();
    if (value.equals(internTable)) {
      let delta;
      if (apiLevel >= 29) {
        delta = 4;
      } else if (apiLevel >= 23) {
        delta = 3;
      } else {
        delta = 5;
      }

      spec = {
        offset: {
          quickGenericJniTrampoline: offset + (delta * pointerSize)
        }
      };

      break;
    }
  }

  if (spec === null) {
    throw new Error('Unable to determine ClassLinker field offsets');
  }

  return spec;
}
```

From AOSP master: https://android.googlesource.com/platform/art/+/refs/heads/master/runtime/class_linker.h#145
```c
  InternTable* intern_table_;

  const bool fast_class_not_found_exceptions_;

  // Trampolines within the image the bounce to runtime entrypoints. Done so that there is a single
  // patch point within the image. TODO: make these proper relocations.
  const void* jni_dlsym_lookup_trampoline_;
  const void* jni_dlsym_lookup_critical_trampoline_;
  const void* quick_resolution_trampoline_;
  const void* quick_imt_conflict_trampoline_;
  const void* quick_generic_jni_trampoline_;
```
Android AOSP master branch and runtime.cc https://android.googlesource.com/platform/art/+/refs/heads/master/runtime/runtime.cc#248

**Comment by amaanq** [comment]
Might be having this same issue here on Android 12, hopefully oleavr can fix this again :)

**Comment by enovella** [comment]
Hey @amaanq,

Try latest Frida 15.1.24 and let us know if the problem persists.

**Comment by BlackFireAlex** [comment]
Tested on Android 12 with 15.1.24 same error as above

**Comment by enovella** [comment]
> Tested on Android 12 with 15.1.24 same error as above

Can you (@BlackFireAlex  @amaanq)  please explain more details about the problem? Similar to the first message of this ticket.

**Comment by BlackFireAlex** [comment]
When I run the frida-servefarm64 on Android 12 I get the error shown in the post

**Comment by amaanq** [comment]
Hope you saw this (@enovella) because having to use my moto g7 power for frida testing atm is annoying... :sweat_smile:
