### ISSUE TITLE
Error: Unable to perform state transition; please file a bug

### ISSUE THREAD

**Issue by abdawoud** [frida/frida-java-bridge#215]
Hi, I'm receiving this fatal error as I try to run `frida-server` on an Android emulator.

```
Error: Unable to perform state transition; please file a bug
    at ot (frida/node_modules/frida-java-bridge/lib/android.js:541:1)
    at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1
    at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)
    at I._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:115:1)
    at I.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:63:1)
    at frida/node_modules/frida-java-bridge/index.js:212:1
    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:11:1)
    at v._performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:211:1)
    at v.perform (frida/node_modules/frida-java-bridge/index.js:192:1)
    at /internal-agent.js:315:6","fileName":"frida/node_modules/frida-java-bridge/lib/android.js
```

The raw errors:
```
{"type":"error","description":"TypeError: r is not a function","stack":"TypeError: r is not a function\n    at it (frida/node_modules/frida-java-bridge/lib/android.js:546:1)\n    at NativeFunction.<anonymous> (<anonymous>)\n    at ot (frida/node_modules/frida-java-bridge/lib/android.js:541:1)\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n    at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n    at I._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:115:1)\n    at I.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:63:1)\n    at frida/node_modules/frida-java-bridge/index.js:212:1\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:11:1)\n    at v._performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:211:1)","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":546,"columnNumber":1}

{"type":"error","description":"Error: Unable to perform state transition; please file a bug","stack":"Error: Unable to perform state transition; please file a bug\n    at ot (frida/node_modules/frida-java-bridge/lib/android.js:541:1)\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n    at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n    at I._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:115:1)\n    at I.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:63:1)\n    at frida/node_modules/frida-java-bridge/index.js:212:1\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:11:1)\n    at v._performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:211:1)\n    at v.perform (frida/node_modules/frida-java-bridge/index.js:192:1)\n    at /internal-agent.js:315:6","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":541,"columnNumber":1}
```

I'm running Cuttlefish emulator (see https://android.googlesource.com/device/google/cuttlefish/)

Other details:
- Android version 11 (API 30)
- CPU ABI: x86_64
- frida-server version: 14.2.14

I would be happy to try fix this error, therefore, any advice would be much appreciated.

Best,
Abdallah

**Comment by pistach3** [comment]
Hi,

I am running into the same issue on `cuttlefish` `x86_64`.
Simply running the `frida-server` binary triggers the error.

Details:
- `frida-server`, `14.2.13`
- `x86_64` cuttlefish, [build ID `7487738`](https://ci.android.com/builds/submitted/7487738/aosp_cf_x86_64_phone-userdebug/latest)
- Android `11` and API `30`

Full error:
```js
{"type":"error","description":"TypeError: r is not a function",
"stack":"TypeError: r is not a function
at it (frida/node_modules/frida-java-bridge/lib/android.js:545:1)
at NativeFunction.<anonymous> (<anonymous>)
at ot (frida/node_modules/frida-java-bridge/lib/android.js:540:1)
at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1
at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)
at I._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:115:1)
at I.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:63:1)
at frida/node_modules/frida-java-bridge/index.js:212:1
at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:11:1)
at v._performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:211:1)",
"fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":545,"columnNumber":1

{"type":"error","description":"Error: Unable to perform state transition; please file a bug",
"stack":"Error: Unable to perform state transition; please file a bug
at ot (frida/node_modules/frida-java-bridge/lib/android.js:540:1)
at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1
at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)
at I._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:115:1)
at I.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:63:1)
at frida/node_modules/frida-java-bridge/index.js:212:1
at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:11:1)
at v._performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:211:1)
at v.perform (frida/node_modules/frida-java-bridge/index.js:192:1)
at /internal-agent.js:313:6",
"fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":540,"columnNumber":1}
```

Tested also with latest frida-server, `15.0.8` with a similar error, different line numbers:
```js
{"type":"error","description":"TypeError: r is not a function","stack":"TypeError: r is not a function
at CallbackContext.lt (frida/node_modules/frida-java-bridge/lib/android.js:547:1)
at NativeFunction.<anonymous> (<anonymous>)
at dt (frida/node_modules/frida-java-bridge/lib/android.js:542:1)
at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1
at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)
at I._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:115:1)
at I.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:63:1)
at frida/node_modules/frida-java-bridge/index.js:212:1
at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:11:1)
at g._performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:211:1)",
"fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":547,"columnNumber":1}

{"type":"error","description":"Error: Unable to perform state transition; please file a bug",
"stack":"Error: Unable to perform state transition; please file a bug
at dt (frida/node_modules/frida-java-bridge/lib/android.js:542:1)
at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1
at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)
at I._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:115:1)
at I.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:63:1)
at frida/node_modules/frida-java-bridge/index.js:212:1
at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:11:1)
at g._performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:211:1)
at g.perform (frida/node_modules/frida-java-bridge/index.js:192:1)
at /internal-agent.js:490:6",
"fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":542,"columnNumber":1}
```

Is this a known limitation/issue?

Either way, I would be happy to help.
