### ISSUE TITLE
Error when starting frida-server-15.0.16-android-arm64

### ISSUE THREAD

**Issue by TonicBoomerKewl** [frida/frida-java-bridge#230]
```powershell
Error: invalid address
    at Object.value [as patchCode](frida/runtime/core.js:170:1)
    at zt (frida/node_modules/frida-java-bridge/lib/android.js:945:1)
    at Ut.activate (frida/node_modules/frida-java-bridge/lib/android.js:998:1)
    at Gt.replace (frida/node_modules/frida-java-bridge/lib/android.js:1045:1)
    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1010:1)
    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:925:1)
    at installLaunchTimeoutRemovalInstrumentation (/internal-agent.js:424:24)
    at init(/internal-agent.js:51:3)
    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:11:1)
    at g._performPendingVmOps (frida/node_modules/frida-java-bridge/index.js:238:1)
```

### [More details...](https://github.com/frida/frida/issues/1820)

**Comment by arkaroy14** [comment]
Same issue here while running frida-server on android 11
`Error: VM::AttachCurrentThread failed: -1
    at o (frida/node_modules/frida-java-bridge/lib/result.js:4)
    at <anonymous> (frida/node_modules/frida-java-bridge/lib/vm.js:25)
    at <anonymous> (frida/node_modules/frida-java-bridge/lib/vm.js:14)
    at Xe (frida/node_modules/frida-java-bridge/lib/android.js:499)
    at Ie (frida/node_modules/frida-java-bridge/lib/android.js:195)
    at Ce (frida/node_modules/frida-java-bridge/lib/android.js:16)
    at _tryInitialize (frida/node_modules/frida-java-bridge/index.js:17)
    at g (frida/node_modules/frida-java-bridge/index.js:9)
    at <anonymous> (frida/node_modules/frida-java-bridge/index.js:317)
    at call (native)
    at o (/_java.js)
    at <anonymous> (/_java.js)
    at <anonymous> (frida/runtime/java.js:1)
    at call (native)
    at o (/_java.js)
    at r (/_java.js)
    at <eval> (frida/runtime/java.js:3)
    at _loadJava (native)
    at get (frida/runtime/core.js:125)
    at <eval> (/frida1.js:1)`
