### ISSUE TITLE
Unable to determine ClassLinker field offsets on Android 12.1

### ISSUE THREAD

**Issue by nukedupe** [frida/frida-java-bridge#258]
This repo is probably the right place for the problem.

### Setup

- Frida: frida-server-15.1.28-android-arm64 from github
- Mobile: Poco F3
- Android OS: crDroidAndroid-12.1-20220715-alioth-v8.7

```
getprop |grep ro.build.version.sdk
[ro.build.version.sdk]: [32]
getprop |grep ro.build.version.release
[ro.build.version.release]: [12]
[ro.build.version.release_or_codename]: [12]
```

### Crash
```
{"type":"error","description":"Error: Unable to determine ClassLinker field offsets",
"stack":"Error: Unable to determine ClassLinker field offsets\n
    at Ye (frida/node_modules/frida-java-bridge/lib/android.js:400:1)\n
    at frida/node_modules/frida-java-bridge/lib/memoize.js:4:1\n
    at ze (frida/node_modules/frida-java-bridge/lib/android.js:193:1)\n
    at Oe (frida/node_modules/frida-java-bridge/lib/android.js:16:1)\n
    at _tryInitialize (frida/node_modules/frida-java-bridge/index.js:29:1)\n
    at new _ (frida/node_modules/frida-java-bridge/index.js:21:1)\n
    at Object.4../lib/android (frida/node_modules/frida-java-bridge/index.js:332:1)\n
    at o (frida/node_modules/browser-pack/_prelude.js:1:1)\n
    at frida/node_modules/browser-pack/_prelude.js:1:1\n
    at Object.22.frida-java-bridge (frida/runtime/java.js:1:1)",
"fileName":"frida/node_modules/frida-java-bridge/lib/android.js",
"lineNumber":400,
"columnNumber":1}
```

I first created the issue directly in the frida repo: https://github.com/frida/frida/issues/2176
But it looks to me like the same problem as here: #163

**Comment by nukedupe** [comment]
Tried to get more information and have a few variables output values.

api:
```
{
  "module": {
    "name": "libart.so",
    "base": "0x70f4895000",
    "size": 10592256,
    "path": "/apex/com.android.art/lib64/libart.so"
  },
  "flavor": "art",
  "addLocalReference": null,
  "JNI_GetCreatedJavaVMs": "0x70f4ce76a0",
  "art::JavaVMExt::AddGlobalRef": "0x70f4ce26c0",
  "art::ReaderWriterMutex::ExclusiveLock": "0x70f4b1e120",
  "art::ReaderWriterMutex::ExclusiveUnlock": "0x70f4b1e4e0",
  "art::Thread::DecodeJObject": "0x70f4efde20",
  "art::ThreadList::SuspendAll": "0x70f4f10670",
  "art::ThreadList::ResumeAll": "0x70f4f10e70",
  "art::ClassLinker::VisitClasses": "0x70f4b3c580",
  "art::ClassLinker::VisitClassLoaders": "0x70f4b3c500",
  "art::StackVisitor::StackVisitor": "0x70f4ed25d0",
  "art::StackVisitor::WalkStack": "0x70f4ecfd10",
  "art::StackVisitor::GetMethod": "0x70f4ed1280",
  "art::Thread::GetLongJumpContext": "0x70f4f04140",
  "art::mirror::Class::GetDescriptor": "0x70f4db17c0",
  "art::Thread::CurrentFromGdb": "0x70f4f03960",
  "art::Dbg::SetJdwpAllowed": "0x70f4b82480",
  "art::Instrumentation::EnableDeoptimization": "0x70f4c62da0",
  "art::Instrumentation::DeoptimizeEverything": "0x70f4c63640",
  "art::Runtime::DeoptimizeBootImage": "0x70f4eb7a20",
  "art::Instrumentation::Deoptimize": "0x70f4c626c0",
  "art::jni::JniIdManager::DecodeMethodId": "0x70f4ceb630",
  "art::interpreter::GetNterpEntryPoint": "0x70f4fee660",
  "art::Monitor::TranslateLocation": "0x70f4dd9580",
  "vm": "0xb4000071a1efd000",
  "kAccCompileDontBother": 33554432,
  "artRuntime": "0xb4000071a1f32a00",
  "artInstrumentation": "0xb4000071a1f32cc0",
  "artHeap": "0xb4000071a1f0b770",
  "artThreadList": "0xb4000071a1f239f0"
}
```

runtimeSpec:
```
{
  "offset": {
    "heap": 424,
    "threadList": 488,
    "internTable": 496,
    "classLinker": 504,
    "jniIdManager": 520,
    "instrumentation": 704,
    "jniIdsIndirection": 1492
  }
}
```

apiLevel: 32

**Comment by nukedupe** [comment]
Temporary solution found see https://github.com/frida/frida/issues/2176#issuecomment-1214024652

**Comment by zhouyunao** [comment]
Hi, @nukedupe .
I'm not familiar with debugging frida/frida-java-bridge, so I'm just curious about how you have got information above.
