### ISSUE TITLE
Unable to determine ClassLinker field offsets

### ISSUE THREAD

**Issue by AkshiTChauhan-max** [frida/frida-java-bridge#260]
{"type":"error","description":"Error: Unable to determine ClassLinker field offsets","stack":"Error: Unable to determine ClassLinker field offsets\n    at Ye (frida/node_modules/frida-java-bridge/lib/android.js:400:1)\n    at frida/node_modules/frida-java-bridge/lib/memoize.js:4:1\n    at ze (frida/node_modules/frida-java-bridge/lib/android.js:193:1)\n    at Oe (frida/node_modules/frida-java-bridge/lib/android.js:16:1)\n    at _tryInitialize (frida/node_modules/frida-java-bridge/index.js:29:1)\n    at new _ (frida/node_modules/frida-java-bridge/index.js:21:1)\n    at Object.4../lib/android (frida/node_modules/frida-java-bridge/index.js:332:1)\n    at o (frida/node_modules/browser-pack/_prelude.js:1:1)\n    at frida/node_modules/browser-pack/_prelude.js:1:1\n    at Object.22.frida-java-bridge (frida/runtime/java.js:1:1)","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":400,"columnNumber":1}
Unable to determine ClassLinker field offsets

Device details 
Android 12L
Ricedroid
Arm64

**Comment by nukedupe** [comment]
Try the temporary solution from here https://github.com/frida/frida/issues/2176#issuecomment-1214024652
