### ISSUE TITLE
An error occurred when starting frida-server on Android

### ISSUE THREAD

**Issue by 4332weizi** [frida/frida-java-bridge#317]
- frida: `16.2.1`
- frida-server: `frida-server-16.2.1-android-arm64`
- divice: `Pixel 7 Pro`
- OS version: `Android 15 VanillalceCream (AP31.240322.027)`

```
cheetah:/ # /data/local/tmp/frida-server &
[1] 28650
cheetah:/ # Unexpectedly timed out while waiting for syscall on ActivityManager thread; please file a bug!
{"type":"error","description":"TypeError: t is not a function","stack":"TypeError: t is not a function
     at frida/node_modules/frida-java-bridge/lib/android.js:1591:1
     at frida/node_modules/frida-java-bridge/lib/class-model.js:113:1
     at CallbackContext.kt (frida/node_modules/frida-java-bridge/lib/android.js:586:1)
     at NativeFunction.<anonymous> (<anonymous>)
     at bt (frida/node_modules/frida-java-bridge/lib/android.js:577:1)
     at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1
     at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)
     at k._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:168:1)
     at k.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:62:1)
     at frida/node_modules/frida-java-bridge/index.js:224:1","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":1591,"columnNumber":1}
{"type":"error","description":"TypeError: Cannot read properties of undefined (reading 'find')","stack":"TypeError: Cannot read properties of undefined (reading 'find')
     at I.value (frida/node_modules/frida-java-bridge/lib/class-factory.js:1014:1)
     at I.value (frida/node_modules/frida-java-bridge/lib/class-factory.js:1030:1)
     at Object.get (frida/node_modules/frida-java-bridge/lib/class-factory.js:742:1)
     at frida/node_modules/frida-java-bridge/index.js:224:1
     at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)
     at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:223:1)
     at _.perform (frida/node_modules/frida-java-bridge/index.js:204:1)
     at /internal-agent.js:490:6","fileName":"frida/node_modules/frida-java-bridge/lib/class-factory.js","lineNumber":1014,"columnNumber":1}
```

**Comment by JoeysWang** [comment]
i meet same issue . android 15 . frida-server-16.3.3-android-arm64.

{
	"type": "error",
	"description": "TypeError: t is not a function",
	"stack": "TypeError: t is not a function\n    at frida/node_modules/frida-java-bridge/lib/android.js:1591:1\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:113:1\n    at CallbackContext.kt (frida/node_modules/frida-java-bridge/lib/android.js:586:1)\n    at NativeFunction.<anonymous> (<anonymous>)\n    at bt (frida/node_modules/frida-java-bridge/lib/android.js:577:1)\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n    at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n    at k._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:168:1)\n    at k.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:62:1)\n    at frida/node_modules/frida-java-bridge/index.js:224:1",
	"fileName": "frida/node_modules/frida-java-bridge/lib/android.js",
	"lineNumber": 1591,
	"columnNumber": 1
}

**Comment by noises1990** [comment]
Encountered the same issue trying to run frida-server-16.3.3-android-arm64 on a VanilaIceCream-level emulator running on a T3 Mac.

{
"type": "error", "description": "TypeError: t is not a function", "stack": "TypeError: t is not a function\n
        at frida/node_modules/frida-java-bridge/lib/android.js:1591:1\n    
        at frida/node_modules/frida-java-bridge/lib/class-model.js:113:1\n    
        at CallbackContext.kt (frida/node_modules/frida-java-bridge/lib/android.js:586:1)\n    
        at NativeFunction.<anonymous> (<anonymous>)\n    
        at bt (frida/node_modules/frida-java-bridge/lib/android.js:577:1)\n    
        at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n    
        at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n    
        at k._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:168:1)\n    
        at k.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:62:1)\n    
        at frida/node_modules/frida-java-bridge/index.js:224:1", "fileName": "frida/node_modules/frida-java-bridge/lib/android.js", "lineNumber": 1591, "columnNumber":1
}

{
"type": "error", "description": "TypeError: Cannot read properties of undefined (reading 'find')", "stack": "TypeError: Cannot read properties of undefined (reading 'find')\n    
        at F.value (frida/node_modules/frida-java-bridge/lib/class-factory.js:1018:1)\n    
        at F.value (frida/node_modules/frida-java-bridge/lib/class-factory.js:1034:1)\n    
        at Object.get (frida/node_modules/frida-java-bridge/lib/class-factory.js:746:1)\n    
        at frida/node_modules/frida-java-bridge/index.js:224:1\n    
        at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    
        at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:223:1)\n    
        at _.perform (frida/node_modules/frida-java-bridge/index.js:204:1)\n    
        at /internal-agent.js:490:6", "fileName": "frida/node_modules/frida-java-bridge/lib/class-factory.js", "lineNumber": 1018, "columnNumber":1
}

**Comment by itormoza** [comment]
{"type":"error","description":"TypeError: t is not a function","stack":"TypeError: t is not a function\n    at frida/node_modules/frida-java-bridge/lib/android.js:1591:1\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:113:1\n    at CallbackContext.kt (frida/node_modules/frida-java-bridge/lib/android.js:586:1)\n    at NativeFunction.<anonymous> (<anonymous>)\n    at bt (frida/node_modules/frida-java-bridge/lib/android.js:577:1)\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n    at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n    at k._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:168:1)\n    at k.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:62:1)\n    at frida/node_modules/frida-java-bridge/index.js:224:1","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":1591,"columnNumber":1}
{"type":"error","description":"TypeError: Cannot read properties of undefined (reading 'find')","stack":"TypeError: Cannot read properties of undefined (reading 'find')\n    at F.value (frida/node_modules/frida-java-bridge/lib/class-factory.js:1018:1)\n    at F.value (frida/node_modules/frida-java-bridge/lib/class-factory.js:1034:1)\n    at Object.get (frida/node_modules/frida-java-bridge/lib/class-factory.js:746:1)\n    at frida/node_modules/frida-java-bridge/index.js:224:1\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:223:1)\n    at _.perform (frida/node_modules/frida-java-bridge/index.js:204:1)\n    at /internal-agent.js:490:6","fileName":"frida/node_modules/frida-java-bridge/lib/class-factory.js","lineNumber":1018,"columnNumber":1}
